In [9]:
import numpy as np # Numpy import 


In [10]:
lst=list(range(1,30))  # pass a list with range
arr1=np.array(lst)  # array function have in np
arr1 # for print 


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [11]:
arr2=np.arange(1,30)   # arange fuction have in np pass a range and print
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [12]:
arr3=np.array([1,2,3,4,5,6,7,8,7, 6,5,4])  # pass a list in array 
arr3

array([1, 2, 3, 4, 5, 6, 7, 8, 7, 6, 5, 4])

In [13]:
arr4=np.zeros((10))  # craete a zero array  and zeroes zeroes function have in  numpyu
arr4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
arr5=np.ones((10))  # ones function have in numpy
arr5

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
arr6=np.zeros((5,5,5))
arr6

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [16]:
arr8=np.ones((5,5))   # two d array in the last have two square bracket 
arr8

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
arr9=np.linspace(1,10,5)  # 1 to 10 is range and 5 is no. give between them randomly it is use of linspace with single bracket
arr9

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [18]:
arr10=np.linspace(1,20,12)
arr10

array([ 1.        ,  2.72727273,  4.45454545,  6.18181818,  7.90909091,
        9.63636364, 11.36363636, 13.09090909, 14.81818182, 16.54545455,
       18.27272727, 20.        ])

In [19]:
arr11=np.arange(0,30)
arr11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [20]:
arr12=np.arange(0,30).reshape(10,3)  # reshape convert 1-d into 2-d  reshape function mean 10 line with three number on each
arr12

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [21]:
arr12=np.arange(0,60).reshape(10,6)
arr12

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [22]:
arr12=np.arange(0,60).reshape(12,5)
arr12

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

# random numbers array gen

In [23]:
arr_1d=np.random.randint(1,5,9) # it give random value from 1 to 5 with 9 value randint function of random and randon function of numpy 
arr_1d

array([1, 4, 1, 4, 1, 3, 3, 3, 2])

In [24]:
arr_2d=np.random.randint(1,5,(5,2)) # creation of two array with random number and randinr is random intergers # 1  to 5 range and 5 to 2 5=row,2=column 
arr_2d

array([[3, 1],
       [4, 2],
       [2, 3],
       [2, 4],
       [3, 3]])

In [25]:
arr_3d=np.random.random(10)
arr_3d

array([0.54938068, 0.67354629, 0.93123164, 0.43150517, 0.35084847,
       0.25035913, 0.4024837 , 0.68157914, 0.80419372, 0.5517858 ])

In [26]:
arr_4d=np.random.random((5,10))
arr_4d

array([[0.74620854, 0.16939562, 0.61962084, 0.60192066, 0.10454669,
        0.66488417, 0.93267573, 0.81529504, 0.67016043, 0.44528161],
       [0.61842083, 0.35046283, 0.10780413, 0.14429937, 0.28018377,
        0.97052454, 0.43244972, 0.13468466, 0.16088776, 0.23196866],
       [0.5354183 , 0.79500195, 0.28375717, 0.33058859, 0.43109808,
        0.83567312, 0.39928815, 0.89947407, 0.96077906, 0.53221046],
       [0.56373129, 0.99148347, 0.78820943, 0.24967439, 0.60350448,
        0.85690459, 0.93499413, 0.69178462, 0.43375513, 0.27220424],
       [0.17994094, 0.55495378, 0.70118284, 0.93954305, 0.97745631,
        0.45441155, 0.45767372, 0.68994407, 0.67468799, 0.48681975]])

#  Array attributes

In [27]:
arr=np.arange(0,60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [28]:
arr.shape  # give the shape of array by the shape function not use parenthesis

(12, 5)

In [29]:
arr.dtype  # find the type of array

dtype('int32')

In [30]:
arr.ndim  # check the dimention of the given array

2

In [31]:
arr.size   # to find no. of element in the array

60

In [32]:
arr.flatten()  # to convert 2-d array into 1-d array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [33]:
arr.ravel()  # to convert 2-d array into 1-d array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [34]:
lst=[[3,4,5,6],[2,3,4,5]]  # MAKE TWO D ARRAY BY A LIST 

In [35]:
aarr_5=np.array(lst)  # convert into array of a list by barray function  
aarr_5


array([[3, 4, 5, 6],
       [2, 3, 4, 5]])

In [36]:
aarr_5.shape # size of arr_5

(2, 4)

In [37]:
aarr_5.T  # transporce

array([[3, 2],
       [4, 3],
       [5, 4],
       [6, 5]])

In [38]:
aarr_5.T.shape

(4, 2)

# Accessing elements from 1D and 2D array
* for 1d array[row_start:end:step/skip]
* for 2d array [row-start:end:skip/step,coloum_start:end:skip/step]

In [39]:
arr_6=np.arange(0,60)
arr_6
arr_6[15]


15

In [40]:
arr_6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [41]:
arr_6[37]

37

In [42]:
arr_6[0:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
arr_6[0:20:2]   # row coloum and skip value

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [44]:
arr_6[0:50:5]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [45]:
for i in arr_6:  # by for loop
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59


In [46]:
arr_7=np.arange(0,60).reshape(12,5)
arr_7
arr_7[1,4]

9

In [47]:
arr_7

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [48]:
arr_7[7]  # row consider only

array([35, 36, 37, 38, 39])

In [49]:
arr_7[7,1:3]

array([36, 37])

In [50]:
arr_7[2,2]  # 2 is row 2 is coloum

12

In [51]:
arr_7[1:5,2:5]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [52]:
arr_7[1,3:5]  # 1 mean  only first row and 3:5 is 3 to 4

array([8, 9])

In [53]:
arr_7[7:8,4]

array([39])

In [54]:
arr_7[7:8,4][0]  # to get in  value form

39

In [55]:
arr_7[7:8,4][0]=100
arr_7  # for change the value 

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38, 100],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59]])

In [56]:
arr_7[11][-1]   # to get last element


59

In [57]:
arr_7[-1][-1] # TO GET LAST VALUE OTHER METHOD

59

In [58]:
arr_7[-1,-1]  # TO GET LAST VALUE OTHER METHOD

59

In [59]:
arr_7[11:,-1]  # TO GET LAST VALUE OTHER METHOD

array([59])

In [60]:
arr_7[11:,-1][0]  # TO GET LAST VALUE OTHER METHOD by value

59

In [61]:
arr_7[11,4]  # TO GET LAST VALUE OTHER METHOD

59

# For 3D array

In [62]:
arr_8=np.array(np.arange(225).reshape(5,15,3))  # 3d array
arr_8

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [63]:
arr_8.shape
# 5  --> table
# 15--> row
# 3 --> column
# 


(5, 15, 3)

In [64]:
arr_8[0][5:] # access 0 table from 5 row 

array([[15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [65]:
arr_8[:,0,:]  # access all table 0 row and 0 column 

array([[  0,   1,   2],
       [ 45,  46,  47],
       [ 90,  91,  92],
       [135, 136, 137],
       [180, 181, 182]])

In [66]:
arr_8[:,0:1,0:1]

array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [67]:
arr_8[:,0:1,0:2]

array([[[  0,   1]],

       [[ 45,  46]],

       [[ 90,  91]],

       [[135, 136]],

       [[180, 181]]])

In [68]:
arr_8[2][3][1] # 2nd table 3rd row and 1st column

100

In [69]:
arr_8[2][3][1] =500

In [70]:
arr_8[0][::-1] # reverse the row

array([[42, 43, 44],
       [39, 40, 41],
       [36, 37, 38],
       [33, 34, 35],
       [30, 31, 32],
       [27, 28, 29],
       [24, 25, 26],
       [21, 22, 23],
       [18, 19, 20],
       [15, 16, 17],
       [12, 13, 14],
       [ 9, 10, 11],
       [ 6,  7,  8],
       [ 3,  4,  5],
       [ 0,  1,  2]])

In [71]:
arr_8[0][::-1,::-1] #  reverse the row

array([[44, 43, 42],
       [41, 40, 39],
       [38, 37, 36],
       [35, 34, 33],
       [32, 31, 30],
       [29, 28, 27],
       [26, 25, 24],
       [23, 22, 21],
       [20, 19, 18],
       [17, 16, 15],
       [14, 13, 12],
       [11, 10,  9],
       [ 8,  7,  6],
       [ 5,  4,  3],
       [ 2,  1,  0]])

In [72]:
arr_8

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 500, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [73]:
arr_8[:,:,0]

array([[  0,   3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36,
         39,  42],
       [ 45,  48,  51,  54,  57,  60,  63,  66,  69,  72,  75,  78,  81,
         84,  87],
       [ 90,  93,  96,  99, 102, 105, 108, 111, 114, 117, 120, 123, 126,
        129, 132],
       [135, 138, 141, 144, 147, 150, 153, 156, 159, 162, 165, 168, 171,
        174, 177],
       [180, 183, 186, 189, 192, 195, 198, 201, 204, 207, 210, 213, 216,
        219, 222]])

In [74]:
arr_8[1][8][2]=800 # change any element
arr_8

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70, 800],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 500, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

# sorting in array

In [75]:
import numpy as np
arr=np.arange(0,30).reshape(10,3)
arr
arr[::-1,:-1]
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [81]:
r_a = arr[::-1,::-1]
r_a

array([[29, 28, 27],
       [26, 25, 24],
       [23, 22, 21],
       [20, 19, 18],
       [17, 16, 15],
       [14, 13, 12],
       [11, 10,  9],
       [ 8,  7,  6],
       [ 5,  4,  3],
       [ 2,  1,  0]])

In [85]:
arr_2=np.array([1,2,3,6,5,7,8,9,3,2,4])
arr_1=np.array([2,5,7,8,9,3,4,5,6,7,3])
arr.sort()

In [86]:
arr_2.sort()  # sort  a array
arr_2

array([1, 2, 2, 3, 3, 4, 5, 6, 7, 8, 9])

In [89]:
arr_2.argsort()  # it return the index of element
arr_2

array([1, 2, 2, 3, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
array=np.array([2,3,4,5])
arry=np.array([])
