In [7]:
import numpy as np # Numpy import 


In [8]:
lst=list(range(1,30))  # pass a list with range
arr1=np.array(lst)  # array function have in np
arr1 # for print 


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [9]:
arr2=np.arange(1,30)   # arange fuction have in np pass a range and print
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [10]:
arr3=np.array([1,2,3,4,5,6,7,8,7, 6,5,4])  # pass a list in array 
arr3

array([1, 2, 3, 4, 5, 6, 7, 8, 7, 6, 5, 4])

In [11]:
arr4=np.zeros((10))  # craete a zero array  and zeroes zeroes function have in  numpyu
arr4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
arr5=np.ones((10))  # ones function have in numpy
arr5

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
arr6=np.zeros((5,5,5))
arr6

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [14]:
arr8=np.ones((5,5))   # two d array in the last have two square bracket 
arr8

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
arr9=np.linspace(1,10,5)  # 1 to 10 is range and 5 is no. give between them randomly it is use of linspace with single bracket
arr9

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [16]:
arr10=np.linspace(1,20,12)
arr10

array([ 1.        ,  2.72727273,  4.45454545,  6.18181818,  7.90909091,
        9.63636364, 11.36363636, 13.09090909, 14.81818182, 16.54545455,
       18.27272727, 20.        ])

In [17]:
arr11=np.arange(0,30)
arr11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [18]:
arr12=np.arange(0,30).reshape(10,3)  # reshape convert 1-d into 2-d  reshape function mean 10 line with three number on each
arr12

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [19]:
arr12=np.arange(0,60).reshape(10,6)
arr12

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [20]:
arr12=np.arange(0,60).reshape(12,5)
arr12

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

# random numbers array gen

In [21]:
arr_1d=np.random.randint(1,5,9) # it give random value from 1 to 5 with 9 value randint function of random and randon function of numpy 
arr_1d

array([2, 3, 2, 1, 4, 4, 1, 2, 4])

In [22]:
arr_2d=np.random.randint(1,5,(5,2)) # creation of two array with random number and randinr is random intergers # 1  to 5 range and 5 to 2 5=row,2=column 
arr_2d

array([[3, 1],
       [3, 2],
       [1, 3],
       [2, 3],
       [4, 2]])

In [23]:
arr_3d=np.random.random(10)
arr_3d

array([0.49683605, 0.62899662, 0.20748133, 0.41756042, 0.97182836,
       0.35896634, 0.00535787, 0.36991162, 0.28166421, 0.78585116])

In [63]:
arr_4d=np.random.random((5,10))
arr_4d

array([[0.97189026, 0.38341051, 0.02105629, 0.12106106, 0.63784213,
        0.30912796, 0.86173989, 0.65500254, 0.94918241, 0.33948143],
       [0.03145599, 0.23295164, 0.68442769, 0.9769958 , 0.30918754,
        0.83815484, 0.06852326, 0.23788121, 0.15926625, 0.09073453],
       [0.8487438 , 0.88864709, 0.15815688, 0.13989224, 0.51653922,
        0.74376577, 0.65728901, 0.15692031, 0.66816356, 0.66759248],
       [0.47708857, 0.1577403 , 0.55440657, 0.508135  , 0.71995988,
        0.22926619, 0.58624217, 0.48579018, 0.62309396, 0.92543711],
       [0.78596779, 0.07503537, 0.45941179, 0.36944075, 0.71563707,
        0.39281847, 0.21410788, 0.43336642, 0.11774093, 0.39386674]])

#  Array attributes

In [25]:
arr=np.arange(0,60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [26]:
arr.shape  # give the shape of array by the shape function not use parenthesis

(12, 5)

In [27]:
arr.dtype  # find the type of array

dtype('int32')

In [28]:
arr.ndim  # check the dimention of the given array

2

In [29]:
arr.size   # to find no. of element in the array

60

In [30]:
arr.flatten()  # to convert 2-d array into 1-d array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [31]:
arr.ravel()  # to convert 2-d array into 1-d array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [32]:
lst=[[3,4,5,6],[2,3,4,5]]  # MAKE TWO D ARRAY BY A LIST 

In [33]:
aarr_5=np.array(lst)  # convert into array of a list by barray function  
aarr_5


array([[3, 4, 5, 6],
       [2, 3, 4, 5]])

In [34]:
aarr_5.shape # size of arr_5

(2, 4)

In [35]:
aarr_5.T  # transporce

array([[3, 2],
       [4, 3],
       [5, 4],
       [6, 5]])

In [36]:
aarr_5.T.shape

(4, 2)

# Accessing elements from 1D and 2D array
* for 1d array[row_start:end:step/skip]
* for 2d array [row-start:end:skip/step,coloum_start:end:skip/step]

In [37]:
arr_6=np.arange(0,60)
arr_6
arr_6[15]


15

In [38]:
arr_6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [39]:
arr_6[37]

37

In [40]:
arr_6[0:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr_6[0:20:2]   # row coloum and skip value

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [42]:
arr_6[0:50:5]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [43]:
for i in arr_6:  # by for loop
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59


In [44]:
arr_7=np.arange(0,60).reshape(12,5)
arr_7
arr_7[1,4]

9

In [45]:
arr_7

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [46]:
arr_7[7]  # row consider only

array([35, 36, 37, 38, 39])

In [47]:
arr_7[7,1:3]

array([36, 37])

In [48]:
arr_7[2,2]  # 2 is row 2 is coloum

12

In [49]:
arr_7[1:5,2:5]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [50]:
arr_7[1,3:5]  # 1 mean  only first row and 3:5 is 3 to 4

array([8, 9])

In [51]:
arr_7[7:8,4]

array([39])

In [52]:
arr_7[7:8,4][0]  # to get in  value form

39

In [53]:
arr_7[7:8,4][0]=100
arr_7  # for change the value 

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38, 100],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59]])

In [54]:
arr_7[11][-1]   # to get last element


59

In [55]:
arr_7[-1][-1] # TO GET LAST VALUE OTHER METHOD

59

In [56]:
arr_7[-1,-1]  # TO GET LAST VALUE OTHER METHOD

59

In [57]:
arr_7[11:,-1]  # TO GET LAST VALUE OTHER METHOD

array([59])

In [58]:
arr_7[11:,-1][0]  # TO GET LAST VALUE OTHER METHOD by value

59

In [59]:
arr_7[11,4]  # TO GET LAST VALUE OTHER METHOD

59

# For 3D array

In [60]:
arr_8=np.array(np.arange(225).reshape(5,15,3))  # 3d array
arr_8

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [61]:
arr_8.shape
# 5  --> table
# 15--> row
# 3 --> column
# 


(5, 15, 3)

In [64]:
arr_8[0][5:] # access 0 table from 5 row 

array([[15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [65]:
arr_8[:,0,:]  # access all table 0 row and 0 column 

array([[  0,   1,   2],
       [ 45,  46,  47],
       [ 90,  91,  92],
       [135, 136, 137],
       [180, 181, 182]])

In [66]:
arr_8[:,0:1,0:1]

array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [67]:
arr_8[:,0:1,0:2]

array([[[  0,   1]],

       [[ 45,  46]],

       [[ 90,  91]],

       [[135, 136]],

       [[180, 181]]])

In [68]:
arr_8[2][3][1] # 2nd table 3rd row and 1st column

100

In [ ]:
arr_8[2][3][1] =500

In [69]:
arr_8[0][::-1] # reverse the column

array([[42, 43, 44],
       [39, 40, 41],
       [36, 37, 38],
       [33, 34, 35],
       [30, 31, 32],
       [27, 28, 29],
       [24, 25, 26],
       [21, 22, 23],
       [18, 19, 20],
       [15, 16, 17],
       [12, 13, 14],
       [ 9, 10, 11],
       [ 6,  7,  8],
       [ 3,  4,  5],
       [ 0,  1,  2]])

In [76]:
arr_8[0][::-1,::-1] #  reverse the row

array([[44, 43, 42],
       [41, 40, 39],
       [38, 37, 36],
       [35, 34, 33],
       [32, 31, 30],
       [29, 28, 27],
       [26, 25, 24],
       [23, 22, 21],
       [20, 19, 18],
       [17, 16, 15],
       [14, 13, 12],
       [11, 10,  9],
       [ 8,  7,  6],
       [ 5,  4,  3],
       [ 2,  1,  0]])

# shorting in array